### ISSUE TITLE
Integration with existing (web) UIs

### ISSUE THREAD

**Issue by GHXST01** [rafpyprog/pymaps#2]
Hey Rafael,

Perhaps a bit more of a difficult "issue" (more of a feature request just like my first one), but it would be nice to perhaps package the export in a friendly way to use in other existing frameworks / UIs.

Arguably you could an iframe to achieve something similar right now, but there has to be a nicer way to achieve the same (or better) result.

Any ideas? I don't mind helping you with this.

**Comment by rafpyprog** [comment]
Actually user can acess the full map HTML from the map.html attribute.
Probably there are dozens user cases for embbeding the map, therefore I am
not sure if we should implement this.
As an example, if an user wants to share a map by email:

with open('mymap.html') as f:
    f.write(map.html)

map.html will render the map at any computer with a browser  and an
internet connection.

Would be nice to be able to save the map as an image, but i still don't
have a clue about how to implement it...

I would like to hear your opinion !






*Atenciosamente,Rafael A. Ribeiro*
*(61**) 998.191.600*

As informações contidas nesta mensagem e nos arquivos anexados são para uso
exclusivo do destinatário aqui indicado e podem conter assuntos comerciais,
de propriedade intelectual ou outras informações confidenciais, protegidas
pelas leis aplicáveis.

Caso não seja o destinatário correto, por favor, notifique o remetente
imediatamente e elimine esta mensagem, uma vez que qualquer revisão,
leitura, cópia e, ou divulgação do conteúdo desta mensagem é estritamente
proibido e não autorizado.

Obrigado por sua cooperação.

2018-02-24 11:55 GMT-03:00 GHXST01 <notifications@github.com>:
